### ISSUE TITLE
Dripzels for roblox clothing isn’t working for me.

### ISSUE THREAD

**Issue by cherry12345x** [SpaceDoritos/Dripzels#1]
A lot of my designer friends who are from different countries it works for them. But for me dripzels doesn’t work. Each time I put the clothing it still loads and just never works it never loads and it doesn’t work for me at all! Old dripzels worked better! I hope you can solve the issue for me. Thanks!

**Comment by cherry12345x** [comment]
![36B3FF5F-5C80-4390-BFAF-718C227BECB6](https://github.com/SpaceDoritos/Dripzels/assets/152957456/76a59665-1e7e-4e71-a376-d913a482dabd)
Thank you for responding. Well I tried on my iPad and on my macbook because I don’t have pc but this is what it keep showing for me even tho I waited 30 mins

**Comment by cherry12345x** [comment]
I did try to upload multiple times but it doesn’t work as if I’m not uploading I even tried with previous clothes that used to work on dripzels just to make sure that the issue isn’t in the clothing but yeah

**Comment by cherry12345x** [comment]
I’m pretty sure it isn’t an issue with my clothes because it works in ingame clothing but I love dripzels more

**Comment by SpaceDoritos** [comment]
It's hard to tell what the issue is this way. You can check the console on your MacBook too. Use the shortcut `Option` + `⌘` + `C`

**Comment by cherry12345x** [comment]
hi so it turns out that it works on my MacBook I just had to use chrome instead of safari! So thank you but when I downloaded chrome on my iPad sadly it didn’t work! I really wanna use it on my iPad instead of laptop but either way thank you so much and the new update is really cool!
